// For Unit Test
#include <MyTools\UnitTestModules.h>
#include <iostream>
#include <MyTools\RandomToolNeedLib\MTRandom.h>
#include <MyTools\MathTool.h>
#include <limits>
#include <array>
#include <ctime>
#pragma comment(lib, "MyTools\\RandomToolNeedLib\\LibForMTRandomAndPrimeSearch.lib")

#include "../CommonClasses/DebugHelpers.h"

// include test target code
#include "../CommonClasses/vector2.h"
#include "../CommonClasses/vector3.h"
#include "../CommonClasses/Image.h"
#include "../CommonClasses/OrthographicCamera.h"
#include "../CommonClasses/Ray.h"
#include "../CommonClasses/Sphere.h"
#include "../CommonClasses/PerspectiveCamera.h"
#include "../CommonClasses/Triangle.h"
#include "../CommonClasses/Scene.h"
#include "../CommonClasses/Polygon.h"
#include "../CommonClasses/ColorTemplate.h"
#include "../CommonClasses/Light.h"
#include "../CommonClasses/Material.h"
#include "../CommonClasses/hvector.h"
#include "../CommonClasses/Transform.h"
#pragma comment(lib, "CommonClasses.lib")

using namespace CommonClass;


RandomTool::MTRandom globalMtr;
const unsigned int G_MAX_INT = 1000;

/*!
    \brief some common configurations for the test.
*/
namespace UserConfig
{
    /*!
    \brief whether let user check some output image file is right,
    if false every check about the Image will be default to be correct.
    */
    const bool LET_USER_CHECK_IMG = false;

    /*!
    \brief common image resolution on width
    */
    const Types::U32 COMMON_PIXEL_WIDTH = 512;

    /*!
    \brief common image resolution on height
    */
    const Types::U32 COMMON_PIXEL_HEIGHT = 512;

    /*!
    \brief common render option, left bound location
    */
    const Types::F32 COMMON_RENDER_LEFT = -3.0f;


    /*!
    \brief common render option, right bound location
    */
    const Types::F32 COMMON_RENDER_RIGHT = +3.0f;


    /*!
    \brief common render option, bottom bound location
    */
    const Types::F32 COMMON_RENDER_BOTTOM = -3.0f;


    /*!
    \brief common render option, right bound location
    */
    const Types::F32 COMMON_RENDER_TOP = +3.0f;

}

/*!
    \brief get random vector3.
    if you want to set the seed, try globalMtr.SetRandomSeed(...);
*/
CommonClass::vector3 GetRandomVector3(bool allowZeroVector = true)
{
    CommonClass::vector3 randVec;
    do
    {
        randVec = CommonClass::vector3((globalMtr.Random() - 0.5f) * (globalMtr.Random(G_MAX_INT) + 1),
            (globalMtr.Random() - 0.5f) * (globalMtr.Random(G_MAX_INT) + 1),
            (globalMtr.Random() - 0.5f) * (globalMtr.Random(G_MAX_INT) + 1));

        // if allowZeroVector is false, loop until a none zero vector
    } while (!allowZeroVector && randVec.m_x == 0.0f && randVec.m_y == 0.0f && randVec.m_z == 0.0f);


    return randVec;
}

/*!
    \brief get random RGB color
    the random number is generated by the globalMtr (which is also used by other functions in this test module).
*/
RGB GetRandomRGB()
{
    return RGB(globalMtr.Random(), globalMtr.Random(), globalMtr.Random());
}

/*!
    \brief let user to check the local image file, this function can be disabled by the constant UserConfig::LET_USER_CHECK_IMG.
    if the user input some number, then we think this test is passed, and return 0 for no error.
*/
unsigned int LetUserCheckJudge(const std::string& msg, bool force = UserConfig::LET_USER_CHECK_IMG)
{
    if (force)
    {
        std::cout << "Please check: " << msg << std::endl
            << "Input '0' ~ '9' for test pass." << std::endl
            << "Else hit enter for some error: ";

        char ch = std::cin.get();

        // if the character is not number, then the image is wrong.
        if (ch < '0' || ch > '9')
        {
            return 1;
        }

        std::cin.clear();
        std::cin.ignore(std::numeric_limits<int>::max(), '\n');
    }

    // no error happend 
    return 0;
}

TEST_MODULE_START

#pragma region Try the testUnit
	TEST_UNIT_START("a test always success")
	TEST_UNIT_END;
#pragma endregion

#pragma region test vector2
	TEST_UNIT_START("test vector2")
		CommonClass::vector2 v2;
        
        errorLogger.LogIfNotEq(v2.m_x, 0.0f);
        errorLogger.LogIfNotEq(v2.m_y, 0.0f);
	TEST_UNIT_END;
#pragma endregion

#pragma region test vector2 +/ -/ *
	TEST_UNIT_START("test vector2 +/ -/ *")

		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 600;
		
		for (int i = 0; i < 200; ++i)
		{
			const Types::F32	comf1(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)), 
								comf2(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf3(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf4(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1));
			CommonClass::vector2 cmp1(comf1, comf2);
			CommonClass::vector2 cmp2(comf3, comf4);

			// cmp1 + cmp2
			errorLogger.LogIfNotEq(
				cmp1 + cmp2,
				CommonClass::vector2(comf1 + comf3, comf2 + comf4));

			// cmp1 - cmp2
			errorLogger.LogIfNotEq(
				cmp1 - cmp2,
				CommonClass::vector2(comf1 - comf3, comf2 - comf4));

			// cmp1 * cmp2
			errorLogger.LogIfNotEq(
				cmp1 * cmp2,
				(comf1 * comf3 + comf2 * comf4));

			// cmp1 * cmp2
			errorLogger.LogIfNotEq(
				CommonClass::dotProd(cmp1, cmp2),
				(comf1 * comf3 + comf2 * comf4));
		}
	TEST_UNIT_END;
#pragma endregion

#pragma region test vector3 +/ -/ *
	TEST_UNIT_START("test vector3 +/ -/ */ X")
		using namespace CommonClass;
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 600;
		
		for (int i = 0; i < 200; ++i)
		{
			const Types::F32	comf1(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)), 
								comf2(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf3(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf4(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf5(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
								comf6(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1));
			CommonClass::vector3 cmp1(comf1, comf2, comf3);
			CommonClass::vector3 cmp2(comf4, comf5, comf6);

			// cmp1 + cmp2
			errorLogger.LogIfNotEq(
				cmp1 + cmp2,
				CommonClass::vector3(comf1 + comf4, comf2 + comf5, comf3 + comf6));

			// cmp1 - cmp2
			errorLogger.LogIfNotEq(
				cmp1 - cmp2,
				CommonClass::vector3(comf1 - comf4, comf2 - comf5, comf3 - comf6));
			
			// cmp1 * cmp2
			errorLogger.LogIfNotEq(
				cmp1 * cmp2,
				(comf1 * comf4 + comf2 * comf5 + comf3 * comf6));

			// cmp1 * cmp2
			errorLogger.LogIfNotEq(
				CommonClass::dotProd(cmp1, cmp2),
				(comf1 * comf4 + comf2 * comf5 + comf3 * comf6));

			// cmp1 X cmp2
			errorLogger.LogIfNotEq(
				CommonClass::crossProd(cmp1, cmp2),
				CommonClass::vector3(
					comf2 * comf6 - comf5 * comf3,
					comf4 * comf3 - comf1 * comf6,
					comf1 * comf5 - comf4 * comf2));

			// vector3 * float
			Types::F32 randomFloat = mtr.Random();
			errorLogger.LogIfNotEq(
				cmp1 * randomFloat,
				vector3(
					comf1 * randomFloat,
					comf2 * randomFloat,
					comf3 * randomFloat)); 
			errorLogger.LogIfNotEq(
				randomFloat * cmp2,
				vector3(
					comf4 * randomFloat,
					comf5 * randomFloat,
					comf6 * randomFloat));

			// - vector3
			errorLogger.LogIfNotEq(
				-cmp1, 
				vector3(-comf1, -comf2, -comf3));
		}
	TEST_UNIT_END;
#pragma endregion

#pragma region test RGBA +/ -/ rgbMulti/ *(scalar)/ /(scalar)
	TEST_UNIT_START("test RGBA +/ -/ */ *(scalar)/ /(scalar)")
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 64;

		/*!
			\brief clamp the channel to [0.0f, 1.0f]
		*/
		auto clampChannel = [](Types::F32 ch)-> Types::F32
		{
			if (ch <= 0.0f)
			{
				return 0.0f;
			}
			else if (ch >= 1.0f)
			{
				return 1.0f;
			}
			else
			{
				return ch;
			}
		};

		for (int i = 0; i < 200; ++i)
		{
			/*!
				make up the RGBA channel
			*/
			const Types::F32	comu1(mtr.Random()),
								comu2(mtr.Random()),
								comu3(mtr.Random()),
								comu4(mtr.Random()),
								comu5(mtr.Random()),
								comu6(mtr.Random()),
								comu7(mtr.Random()),
								comu8(mtr.Random());

			/*!
				scale the RGB with float.
			*/
			const Types::F32	comf1(mtr.Random() * mtr.Random(MAX_RAND_INT)),
								comf2(mtr.Random() * mtr.Random(MAX_RAND_INT));

			RGBA cmp1(comu1, comu2, comu3, comu4);
			RGBA cmp2(comu5, comu6, comu7, comu8);

			/*!
				\brief recover the cmp1's value
			*/
			auto recoverCMP1 = [&cmp1, comu1, comu2, comu3, comu4]()
			{
				cmp1 = RGBA(comu1, comu2, comu3, comu4);
			};

			// default constructor can ignore alpha channel, the alpha of the pixel will be set to max(opaque).
			errorLogger.LogIfNotEq(
                RGBA(comu1, comu2, comu3),
                RGBA(comu1, comu2, comu3, RGBA::ALPHA_CHANNEL_OPAQUE));

			// assign
			cmp1 = cmp2;
			errorLogger.LogIfNotEq(
				cmp1,
                RGBA(comu5, comu6, comu7, comu8));
			recoverCMP1();

			// cmp1 + cmp2
			//cmp1 = cmp1 + cmp2;
			errorLogger.LogIfNotEq( 
				cmp1 + cmp2,
                RGBA(clampChannel(comu1 + comu5), clampChannel(comu2 + comu6), clampChannel(comu3 + comu7), clampChannel(comu4 + comu8)));
			//recoverCMP1();

			// cmp1 - cmp2
            //cmp1 = cmp1 - cmp2;
			errorLogger.LogIfNotEq(
				cmp1 - cmp2,
                RGBA(clampChannel(comu1 - comu5), clampChannel(comu2 - comu6), clampChannel(comu3 - comu7), clampChannel(comu4 - comu8)));
			//recoverCMP1();
			
			// cmp1 * cmp2
			//cmp1 = cmp1 * cmp2,
			errorLogger.LogIfNotEq(
				cmp1 * cmp2,
				RGBA(clampChannel(comu1 * comu5), clampChannel(comu2 * comu6), clampChannel(comu3 * comu7), clampChannel(comu4 * comu8)));
			//recoverCMP1();

			// cmp1 * scalar
			//cmp1.MulRGB(comf1),
			errorLogger.LogIfNotEq(
				cmp1 * comf1,
                RGBA(clampChannel(comu1 * comf1), clampChannel(comu2 * comf1), clampChannel(comu3 * comf1), clampChannel(comu4 * comf1)));
			errorLogger.LogIfNotEq(
			    comf1 * cmp1,       // switch RGBA and scalar
				RGBA(clampChannel(comu1 * comf1), clampChannel(comu2 * comf1), clampChannel(comu3 * comf1), clampChannel(comu4 * comf1)));
			//recoverCMP1();

			// cmp1 / scalar
			//Types::F32 reciprocalComf2 = 1.0f / comf2;
			//cmp1.DivRGB(comf2),
			errorLogger.LogIfNotEq(
				cmp1 / comf2,
				RGBA(clampChannel(comu1 / comf2), clampChannel(comu2 / comf2), clampChannel(comu3 / comf2), clampChannel(comu4 / comf2)));
			//recoverCMP1();
		}
	TEST_UNIT_END;
#pragma endregion

#pragma region test RGB +/ -/ rgbMulti/ *(scalar)/ /(scalar)
	TEST_UNIT_START("test RGB +/ -/ */ *(scalar)/ /(scalar)")
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 64;

		/*!
			\brief clamp the channel to [0.0f, 1.0f]
		*/
		auto clampChannel = [](Types::F32 ch)-> Types::F32
		{
			if (ch <= 0.0f)
			{
				return 0.0f;
			}
			else if (ch >= 1.0f)
			{
				return 1.0f;
			}
			else
			{
				return ch;
			}
		};

		for (int i = 0; i < 200; ++i)
		{
			/*!
				make up the RGBA channel
			*/
			const Types::F32	comu1(mtr.Random()),
								comu2(mtr.Random()),
								comu3(mtr.Random()),
								comu4(mtr.Random()),
								comu5(mtr.Random()),
								comu6(mtr.Random()),
								comu7(mtr.Random()),
								comu8(mtr.Random());

			/*!
				scale the RGB with float.
			*/
			const Types::F32	comf1(mtr.Random() * mtr.Random(MAX_RAND_INT)),
								comf2(mtr.Random() * mtr.Random(MAX_RAND_INT));

			RGB cmp1(comu1, comu2, comu3);
			RGB cmp2(comu5, comu6, comu7);

			/*!
				\brief recover the cmp1's value
			*/
			auto recoverCMP1 = [&cmp1, comu1, comu2, comu3, comu4]()
			{
				cmp1 = RGB(comu1, comu2, comu3);
			};

			// assign
			cmp1 = cmp2;
			errorLogger.LogIfNotEq(
				cmp1,
                RGB(comu5, comu6, comu7));
			recoverCMP1();

			// cmp1 + cmp2
			//cmp1 = cmp1 + cmp2;
			errorLogger.LogIfNotEq( 
				cmp1 + cmp2,
                RGB(clampChannel(comu1 + comu5), clampChannel(comu2 + comu6), clampChannel(comu3 + comu7)));
			//recoverCMP1();

			// cmp1 - cmp2
            //cmp1 = cmp1 - cmp2;
			errorLogger.LogIfNotEq(
				cmp1 - cmp2,
                RGB(clampChannel(comu1 - comu5), clampChannel(comu2 - comu6), clampChannel(comu3 - comu7)));
			//recoverCMP1();
			
			// cmp1 * cmp2
			//cmp1 = cmp1 * cmp2,
			errorLogger.LogIfNotEq(
				cmp1 * cmp2,
				RGB(clampChannel(comu1 * comu5), clampChannel(comu2 * comu6), clampChannel(comu3 * comu7)));
			//recoverCMP1();

			// cmp1 * scalar
			//cmp1.MulRGB(comf1),
			errorLogger.LogIfNotEq(
				cmp1 * comf1,
                RGB(clampChannel(comu1 * comf1), clampChannel(comu2 * comf1), clampChannel(comu3 * comf1)));
			errorLogger.LogIfNotEq(
			    comf1 * cmp1,       // switch RGBA and scalar
				RGB(clampChannel(comu1 * comf1), clampChannel(comu2 * comf1), clampChannel(comu3 * comf1)));
			//recoverCMP1();

			// cmp1 / scalar
			//Types::F32 reciprocalComf2 = 1.0f / comf2;
			//cmp1.DivRGB(comf2),
			errorLogger.LogIfNotEq(
				cmp1 / comf2,
				RGB(clampChannel(comu1 / comf2), clampChannel(comu2 / comf2), clampChannel(comu3 / comf2)));
			//recoverCMP1();
		}
	TEST_UNIT_END;
#pragma endregion

#pragma region cast between RGBA and RGB
    TEST_UNIT_START("cast between RGBA and RGB")
        RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 64;

		/*!
			\brief clamp the channel to [0.0f, 1.0f]
		*/
		auto clampChannel = [](Types::F32 ch)-> Types::F32
		{
			if (ch <= 0.0f)
			{
				return 0.0f;
			}
			else if (ch >= 1.0f)
			{
				return 1.0f;
			}
			else
			{
				return ch;
			}
		};

		for (int i = 0; i < 200; ++i)
		{
			/*!
				make up the RGBA channel
			*/
			const Types::F32	comu1(mtr.Random()),
								comu2(mtr.Random()),
								comu3(mtr.Random()),
								comu4(mtr.Random()),
								comu5(mtr.Random()),
								comu6(mtr.Random()),
								comu7(mtr.Random()),
								comu8(mtr.Random());

			/*!
				scale the RGB with float.
			*/
			const Types::F32	comf1(mtr.Random() * mtr.Random(MAX_RAND_INT)),
								comf2(mtr.Random() * mtr.Random(MAX_RAND_INT));

            RGBA color4(comu1, comu2, comu3, comu4);
            RGB color3(comu5, comu6, comu7);

            errorLogger.LogIfNotEq(Cast(color4), RGB(comu1, comu2, comu3));
            errorLogger.LogIfNotEq(Cast(color3), RGBA(comu5, comu6, comu7, RGBA::ALPHA_CHANNEL_OPAQUE));
            errorLogger.LogIfNotEq(Cast(color3, comu8), RGBA(comu5, comu6, comu7, comu8));
        }
    TEST_UNIT_END;
#pragma endregion

#pragma region check Material construct properties
    TEST_UNIT_START("check Material construct properties")
        using namespace CommonClass;
        const unsigned int MAX_REFLECT_INDEX = 5;
        // reset random seed
        globalMtr.SetRandomSeed(1);

        for (int i = 0; i < 20; ++i)
        {
            RGB color = GetRandomRGB();
            RGB rFresnel0 = GetRandomRGB();
            unsigned int randomReflectIndex = 1 + globalMtr.Random(MAX_REFLECT_INDEX - 1);

            Material mat1;                              // default mat, white color, fresnel coefficient is zero
            Material mat2(color, rFresnel0);            // specific the fresnel coefficient with RGB.
            Material mat3(color, randomReflectIndex);   // calculate fresnel coefficient using reflect index.

            errorLogger.LogIfNotEq(mat1.m_kDiffuse, RGB::WHITE);
            errorLogger.LogIfNotEq(mat1.m_rFresnel_0, RGB::BLACK);

            errorLogger.LogIfNotEq(mat2.m_kDiffuse, color);
            errorLogger.LogIfNotEq(mat2.m_rFresnel_0, rFresnel0);

            // manully calculate the fresnel coefficient.
            Types::F32 reflectIndexToFresnel0 = (randomReflectIndex - 1) * 1.0f / (randomReflectIndex + 1);
            reflectIndexToFresnel0 *= reflectIndexToFresnel0;

            errorLogger.LogIfNotEq(mat3.m_kDiffuse, color);
            errorLogger.LogIfNotEq(mat3.m_rFresnel_0, RGB(reflectIndexToFresnel0, reflectIndexToFresnel0, reflectIndexToFresnel0));

        }
    TEST_UNIT_END;
#pragma endregion

#pragma region vector3 copy constructor
	TEST_UNIT_START("vector3 copy constructor")
		using namespace CommonClass;
		vector3 m3(1.0f, 2.0f, 3.0f);
		vector3 m_toBeError(1.1f, 2.2f, 3.3f);
		vector3 m_copy(m3);

		// construct success
		errorLogger.LogIfFalse(AlmostEqual(m3, m_copy));

		// ensure function AlmostEqual is right
		errorLogger.LogIfTrue(AlmostEqual(m3, m_toBeError));
	TEST_UNIT_END;
#pragma endregion
    
#pragma region vector3 normalize
	TEST_UNIT_START("vector3 normalize")
		using namespace CommonClass;
		using namespace MathTool;
		
		globalMtr.SetRandomSeed(5);

		

		for (int i = 0; i < 20; ++i)
		{
			vector3 v1(GetRandomVector3(false));

			v1 = Normalize(v1);

			errorLogger.LogIfFalse(almost_equal(Length(v1), 1.0f, 8));

			v1.m_x *= 2.0f;
			v1.m_y *= 2.0f;
			v1.m_z *= 3.0f;

			// ensurance, make vector's length not equal to unit.
			errorLogger.LogIfTrue(almost_equal(Length(v1), 1.0f, 8));
		}
	TEST_UNIT_END;
#pragma endregion

#pragma region hvector operation tests
    TEST_UNIT_START("hvector operation tests")
        using namespace CommonClass;
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 600;
		
        for (int i = 0; i < 200; ++i)
        {
            const Types::F32	comf1(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf2(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf3(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf4(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf5(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf6(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf7(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf8(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf9(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1));


            hvector cmp1(comf1, comf2, comf3, comf4);
            hvector cmp2(comf5, comf6, comf7, comf8);

            // declare some hvector for result comparison
            hvector h_plus_h(comf1 + comf5, comf2 + comf6, comf3 + comf7, comf4 + comf8),
                    h_minu_h(comf1 - comf5, comf2 - comf6, comf3 - comf7, comf4 - comf8),
                    h_mult_h(comf1 * comf5, comf2 * comf6, comf3 * comf7, comf4 * comf8),
                    h_dive_h(comf1 / comf5, comf2 / comf6, comf3 / comf7, comf4 / comf8),
                    h_mult_s(comf1 * comf9, comf2 * comf9, comf3 * comf9, comf4 * comf9),
                    s_mult_h(comf1 * comf9, comf2 * comf9, comf3 * comf9, comf4 * comf9),
                    h_dive_s(comf1 / comf9, comf2 / comf9, comf3 / comf9, comf4 / comf9);

            TEST_ASSERT((cmp1 + cmp2)   == h_plus_h);

            TEST_ASSERT((cmp1 - cmp2)   == h_minu_h);

            TEST_ASSERT((cmp1 * cmp2)   == h_mult_h);

            TEST_ASSERT((cmp1 / cmp2)   == h_dive_h);

            hvector temp = cmp1;
            temp += cmp2;
            TEST_ASSERT(     temp       == h_plus_h);

            temp = cmp1;
            temp -= cmp2;
            TEST_ASSERT(     temp       == h_minu_h);

            temp = cmp1;
            temp *= cmp2;
            TEST_ASSERT(     temp       == h_mult_h);

            temp = cmp1;
            temp /= cmp2;
            TEST_ASSERT(     temp       == h_dive_h);

            // Next codes is about operations between hvector and scalar
            // hvector * scalar
            TEST_ASSERT( (cmp1 * comf9) == h_mult_s);

            // scalar * hvector
            TEST_ASSERT( (comf9 * cmp1) == s_mult_h);

            // hvector / scalar
            TEST_ASSERT( (cmp1 / comf9) == h_dive_s);

            // hvector *= scalar
            temp = cmp1;
            temp *= comf9;
            TEST_ASSERT(     temp       == h_mult_s);

            // hvector /= scalar
            temp = cmp1;
            temp /= comf9;
            TEST_ASSERT(     temp       == h_dive_s);

            // Next codes ensure that the comparison is not always return true.
            // next comparison will all return false.
            TEST_ASSERT( ! (h_mult_h    == h_dive_h));
            TEST_ASSERT( ! (h_plus_h    == h_minu_h));

        }
    TEST_UNIT_END;
#pragma endregion

#pragma region transform construct tests
    TEST_UNIT_START("transform construct tests")
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 600;
		
        for (int i = 0; i < 200; ++i)
        {
            TIME_GUARD;
            const Types::F32	comf1(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf2(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf3(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf4(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf5(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf6(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf7(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf8(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf9(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1));

            // Translation 
            Transform trl = Transform::Translation(comf1, comf2, comf3);
            Transform trl_compare(
                1.0f, 0.0f, 0.0f, comf1,
                0.0f, 1.0f, 0.0f, comf2,
                0.0f, 0.0f, 1.0f, comf3,
                0.0f, 0.0f, 0.0f, 1.0f);

            TEST_ASSERT(trl == trl_compare);

            // Rotation transformation
            const Types::F32 cosTheta = std::cosf(comf4),
                             sinTheta = std::sinf(comf4);

            Transform rtx = Transform::RotationX(comf4),
                      rty = Transform::RotationY(comf4),
                      rtz = Transform::RotationZ(comf4);
            
            Transform rtx_compare(
                        1.0f, 0.0f, 0.0f, 0.0f,
                        0.0f, cosTheta, -sinTheta, 0.0f,
                        0.0f, sinTheta, cosTheta, 0.0f,
                        0.0f, 0.0f, 0.0f, 1.0f
                      ),
                      rty_compare(
                          cosTheta, 0.0f, sinTheta, 0.0f,
                          0.0f, 1.0f, 0.0f, 0.0f,
                          -sinTheta, 0.0f, cosTheta, 0.0f,
                          0.0f, 0.0f, 0.0f, 1.0f
                      ),
                      rtz_compare(
                          cosTheta, -sinTheta, 0.0f, 0.0f,
                          sinTheta, cosTheta, 0.0f, 0.0f,
                          0.0f, 0.0f, 1.0f, 0.0f,
                          0.0f, 0.0f, 0.0f, 1.0f
                      );
            
            TEST_ASSERT(rtx == rtx_compare);
            TEST_ASSERT(rty == rty_compare);
            TEST_ASSERT(rtz == rtz_compare);

            TEST_ASSERT(rtx != trl);
            TEST_ASSERT(rty != trl);
            TEST_ASSERT(rtz != trl);
            TEST_ASSERT(rtx != rty);
            TEST_ASSERT(rtz != rty);


            // Viewport transformation
            const Types::U32 
                comu1(mtr.Random(MAX_RAND_INT)),
                comu2(mtr.Random(MAX_RAND_INT)),
                comu3(mtr.Random(MAX_RAND_INT)), 
                comu4(mtr.Random(MAX_RAND_INT));

            // boundries
            const Types::U32 left = comu1, right = comu1 + comu2, bottom = comu3, top = comu3 + comu4;

            Transform viewt = Transform::Viewport(left, right, bottom, top);

            // build nine hvector for view port transformation test.
            std::array<hvector, 9> normalizedPos;
            std::array<Types::F32, 3> constFloats = { -1.0f, 0.0f, 1.0f };
            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {
                    normalizedPos[i * 3 + j] = hvector(constFloats[i], constFloats[j], 0.0f, 1.0f);
                }
            }

            // build nine hvector which should be the vectors transformed by the Viewport transformation.
            std::array<hvector, 9> screenPos;
            std::array<Types::F32, 3> horizontalPoses = {left - 0.5f, (left + right) * 0.5f , right + 0.5f};
            std::array<Types::F32, 3> verticalPoses   = {bottom - 0.5f, (bottom + top) * 0.5f , top + 0.5f};
            for (int i = 0; i < 3; ++i)
            {
                for (int j = 0; j < 3; ++j)
                {
                    screenPos[i * 3 + j] = hvector(horizontalPoses[i], verticalPoses[j], 0.0f, 1.0f);
                }
            }

            // check whether it is true that "normalizedPos" can be transformed to "screenPos" by "viewt"
            for (int i = 0; i < 9; ++i)
            {
                hvector convertToViewport(viewt * normalizedPos[i]);
                TEST_ASSERT(AlmostEqual(screenPos[i], convertToViewport));
            }
        }
        
    TEST_UNIT_END;
#pragma endregion

#pragma region translate and rotate hvector
    TEST_UNIT_START("translate and rotate hvector")

        testConfig.m_skipThisOneTest = true;
        
		RandomTool::MTRandom mtr;
		const unsigned int MAX_RAND_INT = 600;
		
        for (int i = 0; i < 200; ++i)
        {
            TIME_GUARD;
            const Types::F32	comf1(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf2(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf3(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf4(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf5(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf6(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf7(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf8(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1)),
                                comf9(1.0f * mtr.Random(MAX_RAND_INT) / (mtr.Random(MAX_RAND_INT) + 1));


            Transform trl = Transform::Translation(comf1, comf2, comf3);    // translation matrix

            hvector vt(comf5, comf6, comf7);    // the vector used to test translation matrix 

            TEST_ASSERT(
                hvector(comf5 + comf1, comf6 + comf2, comf7 + comf3) 
                == (trl * vt));
            
            const Types::F32 pi_div_2 = Types::Constant::PI_F * 0.5f;

            // build rotations about axis of x/y/z
            const Transform
                rotX = Transform::RotationX(pi_div_2),
                rotY = Transform::RotationY(pi_div_2),
                rotZ = Transform::RotationZ(pi_div_2);
            std::array<Transform, 3> rotations = { rotX, rotY, rotZ }; // each one rotate pi/2 about x,y,z


            std::array<hvector, 8> midVs;   // eight vector point at eight quadrants of the space.
            for (unsigned int i = 0; i < midVs.size(); ++i)
            {
                Types::F32 cx, cy, cz;
                
                cx = (i & 4) ? +1.0f : -1.0f;
                cy = (i & 2) ? +1.0f : -1.0f;
                cz = (i & 1) ? +1.0f : -1.0f;

                midVs[i] = hvector(cx, cy, cz, 1.0f);
            }

            
            /*!
                \brief preRotOrder (previous rotation order)
                assist rotation check, used with array "midVs" and "rotations"
                For example:
                preRotOrder[0][0] = 2 means that rotating vector "midVs[0]" with "rotations[0]" will end up with "midVs[2]"
                preRotOrder[2][1] = 3 means that rotating vector "midVs[2]" with "rotations[1]" will end up with "midVs[3]"
            */
            const unsigned preRotOrder[8][3] = {
                { 2, 1, 4 },
                { 0, 5, 5 },
                { 3, 3, 0 },
                { 1, 7, 1 },
                { 6, 0, 6 },
                { 4, 4, 7 },
                { 7, 2, 2 },
                { 5, 6, 3 }
            };

            /*!
                \brief for each vector of "midVs", rotate them with matrixes in "rotations"
            */
            for (unsigned int i = 0; i < midVs.size(); ++i)
            {
                for (unsigned int j = 0; j < rotations.size(); ++j)
                {
                    TEST_ASSERT(AlmostEqual(rotations[j] * midVs[i], midVs[preRotOrder[i][j]], 1e-7f));

                    // ensure the test not always return true;
                    TEST_ASSERT( ! AlmostEqual(rotations[j] * midVs[i] + hvector(0.5f, 0.0f, 0.0f), midVs[preRotOrder[i][j]], 1e-7f));
                }
            }
            
            // old rotations tests, just rotate axis x/y/z and get the results of x -> y -> z -> x...
            hvector axisx(1.0f, 0.0f, 0.0f, 1.0f);
            hvector axisy(0.0f, 1.0f, 0.0f, 1.0f);
            hvector axisz(0.0f, 0.0f, 1.0f, 1.0f);
            hvector axisx_compare = rotY * axisz;
            hvector axisy_compare = rotZ * axisx;
            hvector axisz_compare = rotX * axisy;

            TEST_ASSERT(AlmostEqual(axisx, axisx_compare, 1e-7f));
            TEST_ASSERT(AlmostEqual(axisy, axisy_compare, 1e-7f));
            TEST_ASSERT(AlmostEqual(axisz, axisz_compare, 1e-7f));

            // next few check ensure that test is not always return true.
            TEST_ASSERT( ! AlmostEqual(axisx, axisy_compare, 1e-7f));
            TEST_ASSERT( ! AlmostEqual(axisy, axisz_compare, 1e-7f));
            TEST_ASSERT( ! AlmostEqual(axisz, axisx_compare, 1e-7f));
            
        }
    TEST_UNIT_END;
#pragma endregion

TEST_MODULE_END

